# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yEW03Rkot_TitoSnGYdf0aFQ-1_36ZEx
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os


# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="Telco Customer Intelligence",
    page_icon="📊",
    layout="wide"
)


# ============================================================
# MODEL PATHS
# ============================================================

CHURN_MODEL_PATH = "/content/churn_model.pkl"
CLTV_MODEL_PATH = "/content/cltv_model.pkl"
KMEANS_MODEL_PATH = "/content/kmeans_model.pkl"
SCALER_PATH = "/content/segment_scaler.pkl"


required_files = [
    CHURN_MODEL_PATH,
    CLTV_MODEL_PATH,
    KMEANS_MODEL_PATH,
    SCALER_PATH
]


missing_files = [
    file for file in required_files
    if not os.path.exists(file)
]


if missing_files:
    st.error("❌ The following model files are missing:")

    for file in missing_files:
        st.write(file)

    st.stop()


# ============================================================
# LOAD MODELS
# ============================================================

@st.cache_resource
def load_models():

    churn_model = joblib.load(CHURN_MODEL_PATH)
    cltv_model = joblib.load(CLTV_MODEL_PATH)
    kmeans_model = joblib.load(KMEANS_MODEL_PATH)
    segment_scaler = joblib.load(SCALER_PATH)

    return (
        churn_model,
        cltv_model,
        kmeans_model,
        segment_scaler
    )


try:

    (
        churn_model,
        cltv_model,
        kmeans_model,
        segment_scaler
    ) = load_models()

except Exception as e:

    st.error("❌ Error while loading the models.")
    st.exception(e)
    st.stop()


# ============================================================
# HELPER FUNCTION
# Align input data types with the fitted model
# ============================================================

def align_to_model_types(model, X):

    """
    Automatically matches the input dataframe data types
    to the data types learned by the fitted preprocessing pipeline.

    This prevents errors such as:

    TypeError: ufunc 'isnan' not supported for the input types

    especially when OneHotEncoder contains numeric categories
    such as Senior Citizen.
    """

    # If the model is not a pipeline with a preprocessor,
    # return the dataframe unchanged.
    if not hasattr(model, "named_steps"):
        return X

    if "preprocessor" not in model.named_steps:
        return X

    preprocessor = model.named_steps["preprocessor"]

    if not hasattr(preprocessor, "transformers_"):
        return X

    for transformer_name, transformer, columns in preprocessor.transformers_:

        if transformer_name == "remainder":
            continue

        columns = list(columns)

        # ----------------------------------------------------
        # Direct OneHotEncoder
        # ----------------------------------------------------

        if hasattr(transformer, "categories_"):

            encoder = transformer

            for col, categories in zip(
                columns,
                encoder.categories_
            ):

                if pd.api.types.is_numeric_dtype(categories):

                    X[col] = pd.to_numeric(
                        X[col],
                        errors="raise"
                    )

                else:

                    X[col] = X[col].astype(str)

        # ----------------------------------------------------
        # Pipeline containing OneHotEncoder / scaler
        # ----------------------------------------------------

        elif hasattr(transformer, "named_steps"):

            found_encoder = False

            for step_name, step in transformer.named_steps.items():

                if hasattr(step, "categories_"):

                    encoder = step
                    found_encoder = True

                    for col, categories in zip(
                        columns,
                        encoder.categories_
                    ):

                        if pd.api.types.is_numeric_dtype(categories):

                            X[col] = pd.to_numeric(
                                X[col],
                                errors="raise"
                            )

                        else:

                            X[col] = X[col].astype(str)

                    break

            # If there is no categorical encoder,
            # treat these columns as numeric.
            if not found_encoder:

                for col in columns:

                    X[col] = pd.to_numeric(
                        X[col],
                        errors="raise"
                    )

        # ----------------------------------------------------
        # Numeric transformer
        # ----------------------------------------------------

        else:

            for col in columns:

                X[col] = pd.to_numeric(
                    X[col],
                    errors="raise"
                )

    return X


# ============================================================
# HEADER
# ============================================================

st.title("📊 Telco Customer Intelligence Dashboard")

st.write(
    "Predict customer churn, estimate customer lifetime value, "
    "and identify customer segments."
)


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.title("Navigation")

page = st.sidebar.radio(
    "Select Page",
    [
        "Customer Prediction",
        "About the Models"
    ]
)


# ============================================================
# CUSTOMER PREDICTION PAGE
# ============================================================

if page == "Customer Prediction":

    st.header("🔍 Customer Analysis")

    st.write(
        "Enter customer information to generate predictions."
    )


    # ========================================================
    # INPUTS
    # ========================================================

    col1, col2, col3 = st.columns(3)


    # --------------------------------------------------------
    # COLUMN 1
    # --------------------------------------------------------

    with col1:

        gender = st.selectbox(
            "Gender",
            ["Male", "Female"]
        )

        senior_citizen = st.selectbox(
            "Senior Citizen",
            [0, 1]
        )

        partner = st.selectbox(
            "Partner",
            ["Yes", "No"]
        )

        dependents = st.selectbox(
            "Dependents",
            ["Yes", "No"]
        )

        tenure_months = st.number_input(
            "Tenure Months",
            min_value=0,
            max_value=100,
            value=12,
            step=1
        )

        phone_service = st.selectbox(
            "Phone Service",
            ["Yes", "No"]
        )


    # --------------------------------------------------------
    # COLUMN 2
    # --------------------------------------------------------

    with col2:

        multiple_lines = st.selectbox(
            "Multiple Lines",
            [
                "Yes",
                "No",
                "No phone service"
            ]
        )

        internet_service = st.selectbox(
            "Internet Service",
            [
                "DSL",
                "Fiber optic",
                "No"
            ]
        )

        online_security = st.selectbox(
            "Online Security",
            [
                "Yes",
                "No",
                "No internet service"
            ]
        )

        online_backup = st.selectbox(
            "Online Backup",
            [
                "Yes",
                "No",
                "No internet service"
            ]
        )

        device_protection = st.selectbox(
            "Device Protection",
            [
                "Yes",
                "No",
                "No internet service"
            ]
        )

        tech_support = st.selectbox(
            "Tech Support",
            [
                "Yes",
                "No",
                "No internet service"
            ]
        )


    # --------------------------------------------------------
    # COLUMN 3
    # --------------------------------------------------------

    with col3:

        streaming_tv = st.selectbox(
            "Streaming TV",
            [
                "Yes",
                "No",
                "No internet service"
            ]
        )

        streaming_movies = st.selectbox(
            "Streaming Movies",
            [
                "Yes",
                "No",
                "No internet service"
            ]
        )

        contract = st.selectbox(
            "Contract",
            [
                "Month-to-month",
                "One year",
                "Two year"
            ]
        )

        paperless_billing = st.selectbox(
            "Paperless Billing",
            [
                "Yes",
                "No"
            ]
        )

        payment_method = st.selectbox(
            "Payment Method",
            [
                "Electronic check",
                "Mailed check",
                "Bank transfer (automatic)",
                "Credit card (automatic)"
            ]
        )

        monthly_charges = st.number_input(
            "Monthly Charges",
            min_value=0.0,
            max_value=2000.0,
            value=70.0,
            step=0.01
        )

        total_charges = st.number_input(
            "Total Charges",
            min_value=0.0,
            max_value=10000.0,
            value=1000.0,
            step=0.01
        )


    st.divider()


    # ========================================================
    # ANALYZE BUTTON
    # ========================================================

    analyze = st.button(
        "🔎 Analyze Customer",
        type="primary",
        use_container_width=True
    )


    if analyze:

        # ====================================================
        # FEATURE LISTS
        # ====================================================

        regression_features = [

            "Gender",
            "Senior Citizen",
            "Partner",
            "Dependents",
            "Tenure Months",
            "Phone Service",
            "Multiple Lines",
            "Internet Service",
            "Online Security",
            "Online Backup",
            "Device Protection",
            "Tech Support",
            "Streaming TV",
            "Streaming Movies",
            "Contract",
            "Paperless Billing",
            "Payment Method",
            "Monthly Charges"

        ]


        churn_features = [

            "Gender",
            "Senior Citizen",
            "Partner",
            "Dependents",
            "Tenure Months",
            "Phone Service",
            "Multiple Lines",
            "Internet Service",
            "Online Security",
            "Online Backup",
            "Device Protection",
            "Tech Support",
            "Streaming TV",
            "Streaming Movies",
            "Contract",
            "Paperless Billing",
            "Payment Method",
            "Monthly Charges",
            "Total Charges"

        ]


        # ====================================================
        # CUSTOMER DATA
        # ====================================================

        customer_data = {

            "Gender": gender,

            "Senior Citizen": senior_citizen,

            "Partner": partner,

            "Dependents": dependents,

            "Tenure Months": tenure_months,

            "Phone Service": phone_service,

            "Multiple Lines": multiple_lines,

            "Internet Service": internet_service,

            "Online Security": online_security,

            "Online Backup": online_backup,

            "Device Protection": device_protection,

            "Tech Support": tech_support,

            "Streaming TV": streaming_tv,

            "Streaming Movies": streaming_movies,

            "Contract": contract,

            "Paperless Billing": paperless_billing,

            "Payment Method": payment_method,

            "Monthly Charges": monthly_charges,

            "Total Charges": total_charges

        }


        # ====================================================
        # CREATE DATAFRAMES
        # ====================================================

        churn_data = pd.DataFrame(
            [
                [
                    customer_data[col]
                    for col in churn_features
                ]
            ],
            columns=churn_features
        )


        cltv_data = pd.DataFrame(
            [
                [
                    customer_data[col]
                    for col in regression_features
                ]
            ],
            columns=regression_features
        )


        # ====================================================
        # ALIGN DATA TYPES WITH SAVED MODELS
        # ====================================================

        try:

            churn_data = align_to_model_types(
                churn_model,
                churn_data
            )

        except Exception as e:

            st.error(
                "❌ Could not align the churn input data "
                "with the saved model."
            )

            st.exception(e)


        try:

            cltv_data = align_to_model_types(
                cltv_model,
                cltv_data
            )

        except Exception as e:

            st.error(
                "❌ Could not align the CLTV input data "
                "with the saved model."
            )

            st.exception(e)


        # ====================================================
        # CHURN PREDICTION
        # ====================================================

        st.divider()

        st.subheader("🚨 Churn Prediction")


        churn_prediction = None
        churn_probability = None


        try:

            churn_prediction = churn_model.predict(
                churn_data
            )[0]


            churn_probability = (
                churn_model.predict_proba(
                    churn_data
                )[0][1]
            )


            if churn_prediction == 1:

                st.error(
                    "⚠️ Customer is predicted to CHURN"
                )

            else:

                st.success(
                    "✅ Customer is predicted to STAY"
                )


            st.metric(
                "Churn Probability",
                f"{churn_probability * 100:.2f}%"
            )


        except Exception as e:

            st.error(
                "❌ Churn prediction failed."
            )

            st.exception(e)


        # ====================================================
        # CLTV / REVENUE PREDICTION
        # ====================================================

        st.subheader("💰 Estimated Customer Value")


        predicted_value = None


        try:

            predicted_value = cltv_model.predict(
                cltv_data
            )[0]


            st.metric(
                "Estimated Customer Lifetime Value",
                f"${predicted_value:,.2f}"
            )


            st.caption(
                "Total Charges is used as the "
                "revenue/CLTV proxy for this project."
            )


        except Exception as e:

            st.error(
                "❌ CLTV prediction failed."
            )

            st.exception(e)


        # ====================================================
        # CUSTOMER SEGMENTATION
        # ====================================================

        st.subheader("👥 Customer Segment")


        if (
            predicted_value is not None
            and churn_probability is not None
        ):

            try:

                estimated_churn_score = (
                    churn_probability * 100
                )


                segmentation_data = pd.DataFrame({

                    "Tenure Months": [
                        float(tenure_months)
                    ],

                    "Total Charges": [
                        float(total_charges)
                    ],

                    "CLTV": [
                        float(predicted_value)
                    ],

                    "Churn Score": [
                        float(estimated_churn_score)
                    ]

                })


                segmentation_scaled = (
                    segment_scaler.transform(
                        segmentation_data
                    )
                )


                segment = (
                    kmeans_model.predict(
                        segmentation_scaled
                    )[0]
                )


                if segment == 0:

                    segment_description = (
                        "Segment 0 – "
                        "Newer / Lower-value Customers"
                    )

                else:

                    segment_description = (
                        "Segment 1 – "
                        "Longer-tenure / Higher-value Customers"
                    )


                st.success(
                    f"Customer Segment: "
                    f"{segment_description}"
                )


                st.info(
                    "Segmentation uses tenure, Total Charges, "
                    "estimated CLTV and estimated churn score."
                )


            except Exception as e:

                st.error(
                    "❌ Segmentation failed."
                )

                st.exception(e)


        # ====================================================
        # CUSTOMER PROFILE
        # ====================================================

        st.divider()

        st.subheader("📋 Customer Profile")


        profile_col1, profile_col2 = st.columns(2)


        with profile_col1:

            st.write(
                f"**Gender:** {gender}"
            )

            st.write(
                f"**Senior Citizen:** "
                f"{'Yes' if senior_citizen == 1 else 'No'}"
            )

            st.write(
                f"**Tenure:** "
                f"{tenure_months} months"
            )

            st.write(
                f"**Contract:** {contract}"
            )

            st.write(
                f"**Internet Service:** "
                f"{internet_service}"
            )


        with profile_col2:

            st.write(
                f"**Monthly Charges:** "
                f"${monthly_charges:,.2f}"
            )

            st.write(
                f"**Total Charges:** "
                f"${total_charges:,.2f}"
            )

            st.write(
                f"**Payment Method:** "
                f"{payment_method}"
            )


            if predicted_value is not None:

                st.write(
                    f"**Estimated CLTV:** "
                    f"${predicted_value:,.2f}"
                )


# ============================================================
# ABOUT THE MODELS PAGE
# ============================================================

else:

    st.header("ℹ️ About the Models")


    # --------------------------------------------------------
    # CHURN
    # --------------------------------------------------------

    st.subheader("🚨 Churn Classification")

    st.write(
        """
        The classification model predicts whether a customer is
        likely to churn based on customer demographics, services,
        contract type, payment method, tenure and charges.
        """
    )

    st.write(
        "**Model:** Logistic Regression"
    )

    st.write(
        "**Class balancing:** Balanced class weights"
    )

    st.write(
        "**ROC-AUC:** 0.9971"
    )

    st.write(
        "**F1-score:** 0.9640"
    )


    st.divider()


    # --------------------------------------------------------
    # CLTV
    # --------------------------------------------------------

    st.subheader(
        "💰 CLTV / Revenue Regression"
    )

    st.write(
        """
        The regression model estimates customer revenue.
        Since the dataset does not provide a separate future
        revenue variable, Total Charges is used as a
        revenue/CLTV proxy.
        """
    )

    st.write(
        "**Best Model:** Random Forest Regressor"
    )

    st.write(
        "**R²:** 0.9987"
    )

    st.write(
        "**MAE:** 55.26"
    )


    st.divider()


    # --------------------------------------------------------
    # SEGMENTATION
    # --------------------------------------------------------

    st.subheader(
        "👥 Customer Segmentation"
    )

    st.write(
        """
        K-Means clustering is used to identify customer groups
        based on Tenure Months, Total Charges, CLTV and
        Churn Score.
        """
    )

    st.write(
        "**Number of Segments:** 2"
    )


    st.divider()


    # --------------------------------------------------------
    # IMPORTANT NOTE
    # --------------------------------------------------------

    st.subheader(
        "⚠️ Important Modeling Note"
    )

    st.info(
        """
        For a new customer, the actual future CLTV and actual
        churn score are not available. Therefore, the application
        uses predicted values as proxies when assigning the
        customer to a segment.
        """
    )